### ISSUE TITLE
Crash when using `ActiveSupport::TestCase#parallelize`

### ISSUE THREAD

**Issue by amomchilov** [minitest-reporters/minitest-reporters#300]
Hey there,

I added `parallelize(workers: :number_of_processors)` to `ActiveSupport::TestCase`, and I got the following error 6 times (once per each of the 6 cores on my machine):

```
/Users/Alex/.gem/ruby/2.6.5/gems/minitest-reporters-1.4.2/lib/minitest/reporters/rubymine_reporter.rb:83:in `before_suite': undefined method `create_suite_started' for nil:NilClass (NoMethodError)
	from /Users/Alex/.gem/ruby/2.6.5/gems/minitest-reporters-1.4.2/lib/minitest/reporters/base_reporter.rb:46:in `before_test'
	from /Users/Alex/.gem/ruby/2.6.5/gems/minitest-reporters-1.4.2/lib/minitest/reporters/rubymine_reporter.rb:91:in `before_test'
	from /Users/Alex/.gem/ruby/2.6.5/gems/minitest-reporters-1.4.2/lib/minitest/reporters.rb:47:in `block in run_with_hooks'
	from /Users/Alex/.gem/ruby/2.6.5/gems/minitest-reporters-1.4.2/lib/minitest/reporters.rb:47:in `each'
	from /Users/Alex/.gem/ruby/2.6.5/gems/minitest-reporters-1.4.2/lib/minitest/reporters.rb:47:in `run_with_hooks'
	from /Users/Alex/.gem/ruby/2.6.5/gems/minitest-5.14.0/lib/minitest.rb:1026:in `run_one_method'
	from /Users/Alex/.gem/ruby/2.6.5/gems/activesupport-6.0.2/lib/active_support/testing/parallelization.rb:89:in `block (3 levels) in start'
	from /Users/Alex/.gem/ruby/2.6.5/gems/minitest-5.14.0/lib/minitest.rb:365:in `on_signal'
	from /Users/Alex/.gem/ruby/2.6.5/gems/minitest-5.14.0/lib/minitest.rb:352:in `with_info_handler'
	from /Users/Alex/.gem/ruby/2.6.5/gems/activesupport-6.0.2/lib/active_support/testing/parallelization.rb:88:in `block (2 levels) in start'
	from /Users/Alex/.gem/ruby/2.6.5/gems/activesupport-6.0.2/lib/active_support/testing/parallelization.rb:75:in `fork'
	from /Users/Alex/.gem/ruby/2.6.5/gems/activesupport-6.0.2/lib/active_support/testing/parallelization.rb:75:in `block in start'
	from /Users/Alex/.gem/ruby/2.6.5/gems/activesupport-6.0.2/lib/active_support/testing/parallelization.rb:74:in `times'
	from /Users/Alex/.gem/ruby/2.6.5/gems/activesupport-6.0.2/lib/active_support/testing/parallelization.rb:74:in `each'
	from /Users/Alex/.gem/ruby/2.6.5/gems/activesupport-6.0.2/lib/active_support/testing/parallelization.rb:74:in `map'
	from /Users/Alex/.gem/ruby/2.6.5/gems/activesupport-6.0.2/lib/active_support/testing/parallelization.rb:74:in `start'
	from /Users/Alex/.gem/ruby/2.6.5/gems/minitest-5.14.0/lib/minitest.rb:138:in `run'
	from /Users/Alex/.gem/ruby/2.6.5/gems/minitest-5.14.0/lib/minitest.rb:68:in `block in autorun'
	from /Users/Alex/.gem/ruby/2.6.5/gems/spring-2.0.2/lib/spring/application.rb:171:in `fork'
	from /Users/Alex/.gem/ruby/2.6.5/gems/spring-2.0.2/lib/spring/application.rb:171:in `serve'
	from /Users/Alex/.gem/ruby/2.6.5/gems/spring-2.0.2/lib/spring/application.rb:141:in `block in run'
	from /Users/Alex/.gem/ruby/2.6.5/gems/spring-2.0.2/lib/spring/application.rb:135:in `loop'
	from /Users/Alex/.gem/ruby/2.6.5/gems/spring-2.0.2/lib/spring/application.rb:135:in `run'
	from /Users/Alex/.gem/ruby/2.6.5/gems/spring-2.0.2/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /opt/rubies/2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/rubies/2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
```

Given #39, I suspect that parallel test is an expected/supported usecase. I tried looking into the bug myself, but I can't even find where `@message_factory` is ever assigned in `Minitest::Reporters::RubyMineReporter`.

Using:
* `minitest-reporters (1.4.2)`
* `rails (6.0.2)`
* Ruby 2.6.5
* RubyMine 2020.1 EAP, or RubyMine 2019.3

**Comment by barrettkingram** [comment]
Is this still an issue with recent versions of RubyMine? I can't reproduce.

**Comment by amomchilov** [comment]
Neither can I, but I'm usually totally different versions of everything now 🤷

**Comment by barrettkingram** [comment]
I'll close for now but will look into this if anyone else experiences issues.
